"""phase12 whatsapp mapping and webhook dedup

Revision ID: 2e93af742989
Revises: e17e6e21fddc
Create Date: 2026-08-15 10:52:35.058040

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2e93af742989'
down_revision: str | None = 'e17e6e21fddc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_webhook_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=200), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_processed_webhook_provider_message_id', 'processed_webhook_event', ['provider_message_id'], unique=True)
    op.add_column('business', sa.Column('whatsapp_phone_number_id', sa.String(length=32), nullable=True))
    op.create_index('uq_business_wa_phone_number_id', 'business', ['whatsapp_phone_number_id'], unique=True, postgresql_where='whatsapp_phone_number_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_business_wa_phone_number_id', table_name='business', postgresql_where='whatsapp_phone_number_id IS NOT NULL')
    op.drop_column('business', 'whatsapp_phone_number_id')
    op.drop_index('uq_processed_webhook_provider_message_id', table_name='processed_webhook_event')
    op.drop_table('processed_webhook_event')
    # ### end Alembic commands ###
