"""phase5 inventory and stock movement

Revision ID: 42672197543c
Revises: 50409ccac723
Create Date: 2026-08-11 08:03:52.261310

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '42672197543c'
down_revision: str | None = '50409ccac723'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('low_stock_threshold >= 0', name='ck_inventory_threshold_non_negative'),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity_non_negative'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', name='uq_inventory_product_id')
    )
    op.create_index('ix_inventory_business_id', 'inventory', ['business_id'], unique=False)
    op.create_table('stock_movement',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('inventory_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('resulting_quantity', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('RESTOCK', 'SALE', 'MANUAL_ADJUSTMENT', 'DAMAGE', name='movementtype', native_enum=False, length=20), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delta <> 0', name='ck_stock_movement_delta_nonzero'),
    sa.CheckConstraint('resulting_quantity >= 0', name='ck_stock_movement_result_non_negative'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_movement_business_id', 'stock_movement', ['business_id'], unique=False)
    op.create_index('ix_stock_movement_business_inventory', 'stock_movement', ['business_id', 'inventory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_movement_business_inventory', table_name='stock_movement')
    op.drop_index('ix_stock_movement_business_id', table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_index('ix_inventory_business_id', table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
