"""phase4 catalog ai draft

Revision ID: 50409ccac723
Revises: 4a67448a6c59
Create Date: 2026-08-11 07:19:45.649667

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '50409ccac723'
down_revision: str | None = '4a67448a6c59'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_ai_draft',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATED', 'FAILED', 'APPROVED', 'REJECTED', name='draftstatus', native_enum=False, length=20), nullable=False),
    sa.Column('source_storage_key', sa.String(length=512), nullable=True),
    sa.Column('source_image_url', sa.String(length=1024), nullable=True),
    sa.Column('source_content_type', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_suggestion', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_suggestion', sa.String(length=64), nullable=True),
    sa.Column('price_amt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('request_key', sa.String(length=80), nullable=True),
    sa.Column('approved_product_id', sa.BigInteger(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_product_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalog_ai_draft_business_id', 'catalog_ai_draft', ['business_id'], unique=False)
    op.create_index('ix_catalog_ai_draft_business_status', 'catalog_ai_draft', ['business_id', 'status'], unique=False)
    op.create_index('uq_catalog_ai_draft_request_key', 'catalog_ai_draft', ['business_id', 'request_key'], unique=True, postgresql_where='request_key IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_catalog_ai_draft_request_key', table_name='catalog_ai_draft', postgresql_where='request_key IS NOT NULL')
    op.drop_index('ix_catalog_ai_draft_business_status', table_name='catalog_ai_draft')
    op.drop_index('ix_catalog_ai_draft_business_id', table_name='catalog_ai_draft')
    op.drop_table('catalog_ai_draft')
    # ### end Alembic commands ###
