"""phase9 invoice

Revision ID: 8a8067dcc7b6
Revises: f2f00bd8231a
Create Date: 2026-08-11 19:15:24.325183

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8a8067dcc7b6'
down_revision: str | None = 'f2f00bd8231a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_counter',
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id', 'year')
    )
    op.create_table('invoice',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', name='invoicestatus', native_enum=False, length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_amt', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amt', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amt', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_reference', sa.String(length=128), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('pdf_storage_key', sa.String(length=512), nullable=True),
    sa.Column('pdf_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_amt >= 0', name='ck_invoice_total_non_negative'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'invoice_number', name='uq_invoice_business_number'),
    sa.UniqueConstraint('order_id', name='uq_invoice_order')
    )
    op.create_index('ix_invoice_business_id', 'invoice', ['business_id'], unique=False)
    op.create_index('ix_invoice_business_status', 'invoice', ['business_id', 'status'], unique=False)
    op.create_table('invoice_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_item_quantity_positive'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_item_business_invoice', 'invoice_item', ['business_id', 'invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoice_item_business_invoice', table_name='invoice_item')
    op.drop_table('invoice_item')
    op.drop_index('ix_invoice_business_status', table_name='invoice')
    op.drop_index('ix_invoice_business_id', table_name='invoice')
    op.drop_table('invoice')
    op.drop_table('invoice_counter')
    # ### end Alembic commands ###
