"""phase10 notification

Revision ID: e17e6e21fddc
Revises: 8a8067dcc7b6
Create Date: 2026-08-11 21:48:02.064233

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e17e6e21fddc'
down_revision: str | None = '8a8067dcc7b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('LOW_STOCK', 'ORDER_CREATED', 'ORDER_CONFIRMED', 'ORDER_CANCELLED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', name='notificationtype', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('related_entity_type', sa.String(length=20), nullable=True),
    sa.Column('related_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedup_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_business_created', 'notification', ['business_id', 'created_at'], unique=False)
    op.create_index('ix_notification_business_read', 'notification', ['business_id', 'is_read'], unique=False)
    op.create_index('uq_notification_dedup', 'notification', ['business_id', 'dedup_key'], unique=True, postgresql_where='dedup_key IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notification_dedup', table_name='notification', postgresql_where='dedup_key IS NOT NULL')
    op.drop_index('ix_notification_business_read', table_name='notification')
    op.drop_index('ix_notification_business_created', table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
