"""phase8 payment

Revision ID: f2f00bd8231a
Revises: 5b495fafec2a
Create Date: 2026-08-11 18:25:03.283549

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f2f00bd8231a'
down_revision: str | None = '5b495fafec2a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.Enum('ONLINE', 'COD', name='paymentmethod', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_order_id', sa.String(length=128), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_business_id', 'payment', ['business_id'], unique=False)
    op.create_index('ix_payment_business_order', 'payment', ['business_id', 'order_id'], unique=False)
    op.create_index('uq_payment_idempotency_key', 'payment', ['business_id', 'idempotency_key'], unique=True, postgresql_where='idempotency_key IS NOT NULL')
    op.create_index('uq_payment_order_success', 'payment', ['order_id'], unique=True, postgresql_where="status = 'SUCCESS'")
    op.create_index('uq_payment_provider_payment_id', 'payment', ['business_id', 'provider_payment_id'], unique=True, postgresql_where='provider_payment_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_payment_provider_payment_id', table_name='payment', postgresql_where='provider_payment_id IS NOT NULL')
    op.drop_index('uq_payment_order_success', table_name='payment', postgresql_where="status = 'SUCCESS'")
    op.drop_index('uq_payment_idempotency_key', table_name='payment', postgresql_where='idempotency_key IS NOT NULL')
    op.drop_index('ix_payment_business_order', table_name='payment')
    op.drop_index('ix_payment_business_id', table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
